export const LOGIN_TRUE = 'LOGIN_TRUE';
export const LOGIN_FALSE = 'LOGIN_FALSE';
export const CHECK_TOKEN = 'CHECK_TOKEN';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const LOAD_LEFT_ELEMENT ='LOAD_LEFT_ELEMENT';
export const REDIRECT_FROM_PARENT_TABLE='REDIRECT_FROM_PARENT_TABLE';


// Load Pay
export const REQUEST_ORDER = 'REQUEST_ORDER';
export const LOAD_ORDER_TRUE = 'LOAD_ORDER_TRUE';
export const LOAD_ORDER_FALSE = 'LOAD_ORDER_FALSE';

export const REQUEST_SUPPLY= 'REQUEST_SUPPLY';
export const LOAD_SUPPLY_TRUE = 'LOAD_SUPPLY_TRUE';
export const LOAD_SUPPLY_FALSE = 'LOAD_SUPPLY_FALSE';

export const REQUEST_PAYMENT= 'REQUEST_PAYMENT';
export const LOAD_PAYMENT_TRUE = 'LOAD_PAYMENT_TRUE';
export const LOAD_PAYMENT_FALSE = 'LOAD_PAYMENT_FALSE';




//Vendor
export const REQUEST_VENDOR= 'REQUEST_VENDOR';
export const LOAD_VENDOR_TRUE = 'LOAD_VENDOR_TRUE';
export const LOAD_VENDOR_FALSE = 'LOAD_VENDOR_FALSE';


//product
export const REQUEST_PRODUCT= 'REQUEST_PRODUCT';
export const LOAD_PRODUCT_TRUE = 'LOAD_PRODUCT_TRUE';
export const LOAD_PRODUCT_FALSE = 'LOAD_PRODUCT_FALSE';

//STORE
export const REQUEST_STORE= 'REQUEST_STORE';
export const LOAD_STORE_TRUE = 'LOAD_STORE_TRUE';
export const LOAD_STORE_FALSE = 'LOAD_STORE_FALSE';

//CONTRACT

export const REQUEST_CONTRACT= 'REQUEST_CONTRACT';
export const LOAD_CONTRACT_TRUE = 'LOAD_CONTRACT_TRUE';
export const LOAD_CONTRACT_FALSE = 'LOAD_CONTRACT_FALSE';

//PRODUCT_VARIANT
export const REQUEST_PRODUCT_VARIANT= 'REQUEST_PRODUCT_VARIANT';
export const LOAD_PRODUCT_VARIANT_TRUE = 'LOAD_PRODUCT_VARIANT_TRUE';
export const LOAD_PRODUCT_VARIANT_FALSE = 'LOAD_PRODUCT_VARIANT_FALSE';
//OPTIONS

export const REQUEST_OPTIONS= 'REQUEST_OPTIONS';
export const LOAD_OPTIONS_TRUE = 'LOAD_OPTIONS_TRUE';
export const LOAD_OPTIONS_FALSE = 'LOAD_OPTIONS_FALSE';

//VARIANT_OPTIONS
export const REQUEST_VARIANT_OPTIONS= 'REQUEST_VARIANT_OPTIONS';
export const LOAD_VARIANT_OPTIONS_TRUE = 'LOAD_VARIANT_OPTIONS_TRUE';
export const LOAD_VARIANT_OPTIONS_FALSE = 'LOAD_VARIANT_OPTIONS_FALSE';
